// The ts-types emitter: a TypeGraphIR to one TypeScript module string.
//
// Per-package: generate the types a repo OWNS, import the ones it BORROWS.
// One interface per owned type-def, parents become `extends`, sealed families
// become a base interface plus a discriminated-union alias. A repo-scoped read
// carries a repo's OWN defs only — every def in the IR is owned. A cross-repo
// dependency surfaces as a `::repo`-qualified REFERENCE inside an owned def
// (a parent or field); it holds no def here, so it is never re-declared — it is
// imported from its owner's package, resolved through the owner→module map.
// Types only, the engine stays the validator. Authored face.
//
// See [[spec - typescript codegen - type-defs to branded ts types preserving name and hierarchy]].

import { CodegenError } from '../../errors.ts'
import { emitEnumValues } from './enum-values.ts'
import type { BrandModel, TypeGraphIR, TypeModel } from '../../ir/ir.ts'
import { emitMetaConstants, emitMetaTypes, type MetaEmitSpec } from './meta.ts'
import { buildNameMap, parseQualified, toTsTypeName, tsPropName } from './names.ts'
import { identifierRefsInShape, refinementDoc, shapeToTs } from './shape.ts'

const HEADER = `// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs.`

const REF_HELPER = `/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of \`T*\`), distinct from an instance \`Ref\`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }`

/** How to resolve borrows and what repo this module is for. */
export interface EmitConfig {
  /** The member repo being generated; stamps the header. Absent for the unscoped/root read. */
  repo?: string
  /** Owner repo → importable module specifier, e.g. `host → @arsumbris/au-host-sdk`. */
  moduleMap?: Map<string, string>
  /** Meta-block emission allowlist: a meta type's bare name → how to emit it. Empty/absent emits nothing. */
  meta?: Map<string, MetaEmitSpec>
  /** When true, a value-mode const appends `satisfies Omit<MetaInterface, 'type'>`. */
  metaSatisfies?: boolean
  /**
   * When true, a top-level FIELD enum also emits a runtime value array
   * (`<Host><Field>Values = [...] as const`). A NAMED enum brand always emits one
   * regardless. See [[decision - 2609092043 - emit runtime enum value arrays, brands always field enums opt-in]].
   */
  enumFieldValues?: boolean
  /** Sink for advisory warnings (e.g. a matchless `--meta` entry). Absent drops them. */
  onWarn?: (message: string) => void
}

interface EmitCtx {
  nameOf: (canonical: string) => string
  isSealed: (canonical: string) => boolean
}

export function emitTypeScript(ir: TypeGraphIR, config: EmitConfig = {}): string {
  const nameMap = buildNameMap(ir) // throws CodegenError on a TS-name collision
  const ctx: EmitCtx = {
    nameOf: (canonical) => nameMap.get(canonical) ?? toTsTypeName(canonical),
    isSealed: (canonical) => ir.byName.get(canonical)?.sealed != null,
  }

  // A repo-scoped read is own-defs-only, so every def in the IR is owned.
  const owned = ir.types

  // Value-mode meta constants, and the meta-interface identifiers their `satisfies`
  // clauses name (folded into borrow resolution, so a cross-repo meta interface imports).
  const metaConfig = config.meta ?? new Map()
  const metaResult = emitMetaConstants(owned, metaConfig, ctx.nameOf, config.metaSatisfies ?? false)
  for (const warning of metaResult.warnings) config.onWarn?.(warning)

  // Type-mode meta: a per-host handled union + a subtype-family payload map.
  const metaTypeResult = emitMetaTypes(ir, owned, metaConfig, ctx.nameOf)
  for (const warning of metaTypeResult.warnings) config.onWarn?.(warning)

  const refSymbols = collectIdentifierRefSymbols(owned, ctx)
  for (const [canonical, symbols] of metaResult.identifierRefs) {
    const set = refSymbols.get(canonical) ?? new Set<string>()
    for (const s of symbols) set.add(s)
    refSymbols.set(canonical, set)
  }

  // Resolve each `::repo`-qualified borrow referenced in the owned output to an import.
  const importsByModule = resolveBorrows(refSymbols, config)

  const importLines = [...importsByModule]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([mod, syms]) => `import type { ${[...syms].sort().join(', ')} } from '${mod}'`)

  const ownedBlocks = owned.map((type) => emitType(type, ctx))

  // Faithful data constants: an enum's literals as an `as const` value array,
  // beside the union type. Brand enums always; field enums when opted in.
  const enumValueBlocks = emitEnumValues(owned, ctx.nameOf, config.enumFieldValues ?? false)

  const header =
    config.repo !== undefined
      ? `// Generated by @arsumbris/type-codegen. Do not edit by hand.\n// Source: au-engine type-defs, repo \`${config.repo}\`.`
      : HEADER

  const parts = [header]
  if (importLines.length > 0) parts.push(importLines.join('\n'))
  parts.push(REF_HELPER, ...ownedBlocks, ...enumValueBlocks, ...metaResult.blocks, ...metaTypeResult.blocks)
  return parts.join('\n\n') + '\n'
}

/**
 * For each borrowed type referenced by identifier in the owned output, resolve
 * its owner to a module and collect an import, or error. A borrow referenced
 * ONLY via `Ref<'name'>` produces no TS and is not considered here. Throws
 * naming every unresolvable borrow.
 *
 * A borrow is a `::repo`-qualified cross-repo REFERENCE, whose owner rides in
 * the name (`widget::xr-base`) and whose def is NOT in this scoped read (the
 * read is own-defs-only). Its owner maps to a module via `--module owner=spec`;
 * an owner with no module entry is a hard error — we hold no def to generate
 * locally. See [[type repo qualifier::au-engine]].
 */
function resolveBorrows(refSymbols: Map<string, Set<string>>, config: EmitConfig): Map<string, Set<string>> {
  const moduleMap = config.moduleMap ?? new Map<string, string>()
  const importsByModule = new Map<string, Set<string>>()
  const unresolved: { name: string; owner: string }[] = []

  for (const [canonical, symbols] of refSymbols) {
    const owner = parseQualified(canonical).owner
    if (owner === null) continue // an owned type referenced by another owned type — no import
    const module = moduleMap.get(owner)
    if (module !== undefined) {
      const set = importsByModule.get(module) ?? new Set<string>()
      for (const s of symbols) set.add(s)
      importsByModule.set(module, set)
    } else {
      unresolved.push({ name: canonical, owner })
    }
  }

  if (unresolved.length > 0) {
    const list = unresolved.map((u) => `'${u.name}' (owner '${u.owner}')`).join(', ')
    throw new CodegenError(
      `borrowed type(s) have no module mapping: ${list}. add the owner to --module-map / --module.`,
    )
  }
  return importsByModule
}

/**
 * Per canonical type name referenced by identifier in the owned types, the exact
 * TS symbols the output uses — a sealed parent through its `Base` interface, a
 * field reference through the type's own name. Drives the import symbol set.
 */
function collectIdentifierRefSymbols(owned: TypeModel[], ctx: EmitCtx): Map<string, Set<string>> {
  const refs = new Map<string, Set<string>>()
  const add = (canonical: string, symbol: string): void => {
    const set = refs.get(canonical) ?? new Set<string>()
    set.add(symbol)
    refs.set(canonical, set)
  }
  for (const type of owned) {
    // A brand emits as a type alias over its shape; that shape (a union / tuple)
    // may name a borrowed identifier, so collect its refs like a field's.
    if (type.brand !== undefined) {
      for (const canonical of identifierRefsInShape(type.brand.shape)) add(canonical, ctx.nameOf(canonical))
      continue // a brand has no parents / fields of its own
    }
    // A sealed parent is extended through its `Base` interface, never its union alias.
    for (const parent of type.parents) add(parent, ctx.isSealed(parent) ? `${ctx.nameOf(parent)}Base` : ctx.nameOf(parent))
    for (const field of type.fields) {
      if (field.shape === null) continue
      for (const canonical of identifierRefsInShape(field.shape)) add(canonical, ctx.nameOf(canonical))
    }
  }
  return refs
}

/**
 * A parent reference, as `Omit<Parent, 'type'>`.
 * - a sealed parent is extended through its `Base` interface, never its union alias.
 * - `Omit<_, 'type'>` strips the parent's `type` discriminant so the child's own
 *   `type` always wins. A subtype carries a literal (`type: '<name>'`); a parent
 *   may carry a disjoint literal (an abstract kind base mis-emitted as a leaf in a
 *   per-package read) which a child cannot narrow, TS2430. Omitting it sidesteps
 *   that, deterministically and across the package boundary, where the parent's
 *   emission is invisible to this read. The parent's `type` is never read bare, so
 *   stripping it has no runtime effect.
 *   See [[decision - 2606301731 - codegen omits parent type discriminant on extends]].
 */
function emitExtends(parents: string[], ctx: EmitCtx): string {
  if (parents.length === 0) return ''
  const mapped = parents.map((p) => {
    const sym = ctx.isSealed(p) ? `${ctx.nameOf(p)}Base` : ctx.nameOf(p)
    return `Omit<${sym}, 'type'>`
  })
  return ` extends ${mapped.join(', ')}`
}

/**
 * The universal `^:` block-id slot every record may carry (universal
 * addressability). Emitted as an optional field on every generated interface,
 * so a consumer that needs stable per-record identity (selection, undo, future
 * instance references) reads it directly instead of hand-adding an `id`.
 *
 * Spelled with the faithful `'^'` key, NOT a friendly `id`. `^` is not a legal
 * au field name, so the quoted key can NEVER collide with a real declared field;
 * an `id` alias could silently overlap one, which we categorically avoid.
 * See [[decision - 2608101212 - block-id slot spelled as the faithful caret key]].
 */
const BLOCK_ID_FIELD =
  "  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */\n  '^'?: string"

/** The `type` discriminant a type carries: its literal/keyword and whether it is optional. */
interface Discriminant {
  /** The TS type of the slot: `string` for an open base, `'<name>'` for a leaf. */
  literal: string
  /** True for an open base (`type?: string`), false for a leaf's required literal. */
  optional: boolean
}

/**
 * The `type` discriminant a type carries, or null. An instance's type IS its
 * claim, so a type in an extension hierarchy surfaces it as a discriminant.
 * - a sealed parent carries none: its union alias narrows instead.
 * - a non-sealed ROOT (no parents) → `type?: string`. It is an open base: it must
 *   be extension-ready from its OWN package, since extending it elsewhere
 *   requires vendoring a copy that imports this generated base, and a subtype's
 *   literal only assigns to a `string` discriminant. A childless root is treated
 *   the same — it could be vendored and extended later, and its instance carries
 *   its own `type` claim regardless.
 * - a mid-tier type (extended, with parents) → `type?: string`, a base for its
 *   children; a closed literal would not be satisfiable by their literals.
 * - a leaf (has parents, not itself extended) → `type: '<name>'`, the literal it
 *   narrows on. Covers a sealed-family leaf and an open subtype alike.
 *
 * The open-base `type` is OPTIONAL: the engine infers a pinned inline record's
 * type from its slot, so a bare `{ x, y, z }` validates with no `type:`. A
 * required `type: string` was stricter than the wire and forced consumers to
 * `Omit<_, 'type'>`. A leaf's literal stays required — it is the mandatory,
 * single-valued claim the union narrows on. See the spec's discriminant rule.
 *
 * Base detection is "is a root, or is extended", NOT "is extended in this read".
 * A base whose subtypes are all in other packages would otherwise miss its
 * `type: string` and break those vendored extensions.
 */
function discriminant(type: TypeModel): Discriminant | null {
  if (type.sealed !== null) return null
  if (type.parents.length === 0) return { literal: 'string', optional: true }
  if (type.extended) return { literal: 'string', optional: true }
  return { literal: `'${type.name}'`, optional: false }
}

/**
 * A `#:` docstring as a JSDoc comment at `indent`, or `''` when absent. A single
 * line renders inline `/** … *​/`; multiple lines render a starred block.
 */
function jsdoc(doc: string | undefined, indent: string): string {
  if (doc === undefined || doc === '') return ''
  // Escape an embedded comment terminator so a docstring like `e.g. "**/*.ts"` cannot close the
  // JSDoc block early (which would emit invalid TS). `*\/` renders as `*/` but is not a terminator.
  const lines = doc.replaceAll('*/', '*\\/').split('\n')
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`
  const inner = lines.map((l) => `${indent} * ${l}`.trimEnd()).join('\n')
  return `${indent}/**\n${inner}\n${indent} */\n`
}

function emitFields(type: TypeModel, ctx: EmitCtx): string {
  const lines: string[] = []
  const disc = discriminant(type)
  // Engine-universal slots first: the `type` claim, then the `^:` block id.
  if (disc !== null) lines.push(`  type${disc.optional ? '?' : ''}: ${disc.literal}`)
  lines.push(BLOCK_ID_FIELD)
  for (const field of type.fields) {
    const optional = field.required ? '' : '?'
    const tsType = field.shape ? shapeToTs(field.shape, ctx.nameOf) : `unknown /* unparsed: ${field.sourceShape} */`
    // A `refined` field's predicate can't ride the TS type, so it joins the JSDoc.
    const refNote = field.shape ? refinementDoc(field.shape) : null
    const doc = [field.doc, refNote].filter((d): d is string => d !== undefined && d !== null && d !== '').join('\n')
    lines.push(`${jsdoc(doc, '  ')}  ${tsPropName(field.name)}${optional}: ${tsType}`)
  }
  return `{\n${lines.join('\n')}\n}`
}

/**
 * Whether a brand's shape is NOMINAL — a scalar (`primitive`/`refined`) or a
 * `tuple`. A nominal brand carries a `& { __brand }` tag so it is distinct from
 * its bare representation (`meter` is not `second`, `rect` is not `mat2`). An
 * `enum` or `union` shape is STRUCTURAL: the literal union / branch union already
 * carries the distinction, and a brand tag would only cost authoring ergonomics
 * (every member / branch would need a cast). See the spec's brand-encoding rule.
 */
function isNominalBrandShape(brand: BrandModel): boolean {
  const k = brand.shape.kind
  return k === 'primitive' || k === 'refined' || k === 'tuple'
}

/**
 * A brand def's combined JSDoc: the type's own `#:` head doc, a `refined`
 * predicate note, and per-member enum docs as a bullet list (declaration order),
 * joined by blank lines. `undefined` when there is nothing to say.
 */
function brandDoc(type: TypeModel, brand: BrandModel): string | undefined {
  const parts: string[] = []
  if (type.doc !== undefined && type.doc !== '') parts.push(type.doc)
  const refNote = refinementDoc(brand.shape)
  if (refNote !== null) parts.push(refNote)
  if (brand.shape.kind === 'enum' && brand.memberDocs !== undefined) {
    const docs = brand.memberDocs
    const lines = brand.shape.members.filter((m) => docs[m] !== undefined).map((m) => `- \`${m}\`: ${docs[m]}`)
    if (lines.length > 0) parts.push(lines.join('\n'))
  }
  return parts.length > 0 ? parts.join('\n\n') : undefined
}

/**
 * A brand def (`shape:` instead of `fields:`) as a type ALIAS over its underlying
 * shape — never an interface, so no `type` discriminant, `^` block-id, or
 * `extends`. A nominal shape (scalar / tuple) gets a `& { readonly __brand }`
 * tag over the bare name; an enum / union stays structural (the literal / branch
 * union is already distinct). Member docs and refinement notes ride the JSDoc.
 */
function emitBrand(type: TypeModel, brand: BrandModel, ctx: EmitCtx): string {
  const ts = ctx.nameOf(type.name)
  const base = shapeToTs(brand.shape, ctx.nameOf)
  const body = isNominalBrandShape(brand)
    ? `${base} & { readonly __brand: '${parseQualified(type.name).bare}' }`
    : base
  return `${jsdoc(brandDoc(type, brand), '')}export type ${ts} = ${body}`
}

function emitType(type: TypeModel, ctx: EmitCtx): string {
  const ts = ctx.nameOf(type.name)
  if (type.brand !== undefined) return emitBrand(type, type.brand, ctx)
  if (type.sealed) {
    // A sealed parent: the shared shape as a `Base` interface, plus the union
    // of its leaves as the inhabitable type a consumer holds. The def docstring
    // rides the union alias, the name a consumer references.
    const base = `export interface ${ts}Base${emitExtends(type.parents, ctx)} ${emitFields(type, ctx)}`
    const union = `${jsdoc(type.doc, '')}export type ${ts} = ${type.sealed.map(ctx.nameOf).join(' | ')}`
    return `${base}\n\n${union}`
  }
  return `${jsdoc(type.doc, '')}export interface ${ts}${emitExtends(type.parents, ctx)} ${emitFields(type, ctx)}`
}
